language: objective-c
osx_image: xcode7.3
script: make
notifications:
    irc:
        channels:
          - "irc.freenode.net##kwm"
        template:
            - "%{author} @ %{repository_name} -> %{branch} - Build:#%{build_number} : %{message} - Commit: %{commit_message}"
        use_notice: true
        skip_join: true
